source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!

target 'PreferabliDataSDKDemo' do
    pod 'PreferabliDataSDK', :git => 'https://github.com/winering/preferabli-data-sdk-ios.git'
#    pod 'PreferabliDataSDK', :path => '../../preferabli-data-sdk-ios'
    pod 'TTGSnackbar'
end
