source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'
use_frameworks!

target 'PreferabliDataSDKDemo' do
    pod 'PreferabliDataSDK', :git => 'https://github.com/winering/preferabli-data-sdk-ios.git'
#    pod 'PreferabliDataSDK', :path => '../../preferabli-data-sdk-ios'
    pod 'TTGSnackbar'
#    pod 'DoccDemo', :git=> 'https://github.com/haifengkao/DoccDemo'
end
